version: '2'

services:
  elk:
    build: .
    environment:
      OPTS: -Dindex.number_of_shards=1 -Dindex.number_of_replicas=0
      LOGSTASH_START: 0
    ports:
      - "9200:9200"
      - "5601:5601"
    volumes:
      - ./elk-post-hooks.sh:/usr/local/bin/elk-post-hooks.sh
      - ./mappings.json:/_config/mappings.json
      - ./kibana:/_config/kibana/
      # see https://github.com/elastic/kibana/issues/3709 for pushing kibana index patteerns
      # https://github.com/nh2/kibana-importer
      # this container has python3 :-)
    networks:
      - elknet

networks:
  elknet:

